name: 'Setup CI environment'
description: 'Common part to tweak CI runner environment'
runs:
  using: 'composite'
  steps:
    - run: |
        # Set CMAKE_BUILD_PARALLEL_LEVEL environment variable to
        # limit the number of parallel jobs for build/test step.
        # Try the exotic Darwin way at first and fallback to nproc
        # that is the default for the normal systems.
        NPROC=$(sysctl -n hw.logicalcpu 2>/dev/null || nproc)
        echo CMAKE_BUILD_PARALLEL_LEVEL=$(($NPROC + 1)) | tee -a $GITHUB_ENV
      shell: bash
    - run: |
        # Set BUILDDIR environment variable to specify LuaJIT
        # build directory.
        echo "BUILDDIR=${{ runner.temp }}/build-${{ github.run_id }}" | tee -a $GITHUB_ENV
      shell: bash
