name: Setup CI environment for testing with sanitizers on Linux
description: Common part to tweak Linux CI runner environment for sanitizers
runs:
  using: composite
  steps:
    - name: Setup CI environment
      uses: ./.github/actions/setup
    - name: Set CMAKE_BUILD_PARALLEL_LEVEL
      run: |
        # Set CMAKE_BUILD_PARALLEL_LEVEL environment variable to
        # limit the number of parallel jobs for build/test step.
        NPROC=$(nproc)
        echo CMAKE_BUILD_PARALLEL_LEVEL=$(($NPROC + 1)) | tee -a $GITHUB_ENV
      shell: bash
    - name: Install build and test dependencies
      run: |
        apt -y update
        apt -y install clang-11 cmake ninja-build make perl
      shell: bash
    - name: Set Clang as a default toolchain
      run: |
        echo CC=clang-11 | tee -a $GITHUB_ENV
      shell: bash
