name: "Exotic builds testing"

on:
  push:
    branches-ignore:
      - '**-notest'
      - 'upstream-**'
    tags-ignore:
      - '**'

concurrency:
  # An update of a developer branch cancels the previously
  # scheduled workflow run for this branch. However, the default
  # branch, and long-term branch (tarantool-1.10, tarantool-2.8,
  # etc.) workflow runs are never canceled.
  #
  # We use a trick here: define the concurrency group as 'workflow
  # run ID' + # 'workflow run attempt' because it is a unique
  # combination for any run. So it effectively discards grouping.
  #
  # XXX: we cannot use `github.sha` as a unique identifier because
  # pushing a tag may cancel a run that works on a branch push
  # event.
  group: ${{ (
    github.ref == 'refs/heads/tarantool' ||
    startsWith(github.ref, 'refs/heads/tarantool-')) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  test-exotic:
    strategy:
      fail-fast: false
      matrix:
        BUILDTYPE: [Debug, Release]
        ARCH: [x86_64]
        GC64: [ON, OFF]
        FLAVOR: [dualnum, checkhook]
        include:
          - BUILDTYPE: Debug
            CMAKEFLAGS: -DCMAKE_BUILD_TYPE=Debug -DLUA_USE_ASSERT=ON -DLUA_USE_APICHECK=ON
          - BUILDTYPE: Release
            CMAKEFLAGS: -DCMAKE_BUILD_TYPE=RelWithDebInfo
          - FLAVOR: dualnum
            FLAVORFLAGS: -DLUAJIT_NUMMODE=2
          - FLAVOR: checkhook
            FLAVORFLAGS: -DLUAJIT_ENABLE_CHECKHOOK=ON
    runs-on: [self-hosted, regular, Linux, '${{ matrix.ARCH }}']
    name: >
      LuaJIT ${{ matrix.FLAVOR }}
      (Linux/${{ matrix.ARCH }})
      ${{ matrix.BUILDTYPE }}
      GC64:${{ matrix.GC64 }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: setup Linux
        uses: ./.github/actions/setup-linux
      - name: configure
        run: >
          cmake -S . -B ${{ env.BUILDDIR }}
          -G Ninja
          ${{ matrix.CMAKEFLAGS }}
          ${{ matrix.FLAVORFLAGS }}
          -DLUAJIT_ENABLE_GC64=${{ matrix.GC64 }}
      - name: build
        run: cmake --build . --parallel
        working-directory: ${{ env.BUILDDIR }}
      - name: test
        run: cmake --build . --parallel --target test
        working-directory: ${{ env.BUILDDIR }}
